name: Install Qt simple
description: Install Qt on your Github Actions workflows with just one simple action
author: orestonce
branding:
  icon: package
  color: green
inputs:
  dir:
    description: Directory to install Qt
    required: false
    default: "qt_static_install"
  version:
    description: Version of Qt to install
    required: true
    default: "Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104"

runs:
  using: composite
  steps:
  - name: Call Sub Workflow
    uses: actions/include@v1
    with:
      path: './sub-workflow-windows.yml'
      dir: ${{ inputs.dir }}
      version: ${{ inputs.version }}
      
  - name: show windows message
    shell: powershell
    run: |
      echo "xxxx-windows-begin"
      echo "${{ inputs.dir }}"
      echo "${{ inputs.version }}"
      echo "xxxx-windows-end"
      
runs: #install_job_macos
  using: composite
  steps:
  - name: Call Sub Workflow
    uses: actions/include@v1
    with:
      path: './sub-workflow-macos.yml'
      dir: ${{ inputs.dir }}
      version: ${{ inputs.version }}
      
  - name: show macos message
    shell: bash
    run: |
      echo "xxxx-macos-begin"
      echo "${{ inputs.dir }}"
      echo "${{ inputs.version }}"
      echo "xxxx-macos-end"