name: Install Qt simple
description: Install Qt on your Github Actions workflows with just one simple action
author: orestonce
branding:
  icon: package
  color: green

inputs:
    dir:
      description: Directory to install Qt
      required: false
      default: "qt_install"
    version:
      description: Version of Qt to install
      required: true

runs:
    using: composite
    steps:
      - name: Cache Primes
        id: install_qt
        uses: actions/cache@v3
        with:
          path: ${{ inputs.dir }}
          key: ${{ inputs.version }}
      - name: install Qt to dir, windows
        shell: powershell
        if: runner.os == 'windows' && steps.install_qt.outputs.cache-hit != 'true'
        run: |
          switch ( "${{ inputs.version }}" ) {
            "Qt4.8.7-Windows-x86-MinGW4.9.4-20200104" {
              $var_qt_URL = "https://github.com/orestonce/install-qt/releases/download/qt4.8.7/Qt4.8.7-Windows-x86-MinGW4.9.4-20200104.7z"
              $var_mingw_URL = "https://github.com/orestonce/install-qt/releases/download/qt4.8.7/i686-4.9.4-release-posix-dwarf-rt_v5-rev0.7z"
              $var_qt_dir_name = "Qt4.8.7-Windows-x86-MinGW4.9.4-20200104"
              $var_mingw_dir_name = "mingw32"
              $var_md5_qt_7z = "8923E65F207498B957731796C99C4D1E"
              $var_md5_mingw_7z = "7A5EC2F88844351C177509DB9DBEF9AE"
              break
            }
            "Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104" {
              $var_qt_URL = "https://github.com/orestonce/install-qt/releases/download/qt5.6.3/Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104-ManualPatchSslLib.7z"
              $var_mingw_URL = "https://github.com/orestonce/install-qt/releases/download/qt5.6.3/i686-4.9.4-release-posix-dwarf-rt_v5-rev0.7z"
              $var_qt_dir_name = "Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104"
              $var_mingw_dir_name = "mingw32"
              $var_md5_qt_7z = "9FC57FE49FF50D7F1BC75B0719899711"
              $var_md5_mingw_7z = "7A5EC2F88844351C177509DB9DBEF9AE"
              break
            }
            "Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104" {
              $var_qt_URL = "https://github.com/orestonce/install-qt/releases/download/qt5.15.7/Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104.7z"
              $var_mingw_URL = "https://github.com/orestonce/install-qt/releases/download/qt5.15.7/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z"
              $var_qt_dir_name = "Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull"
              $var_mingw_dir_name = "mingw32"
              $var_md5_qt_7z = "2CB541AF6FC373C2C49BFABA739DBCB1"
              $var_md5_mingw_7z = "07583A272282F71E6E8701B2BF64FAFE"
              break
            }
            "Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104" {
              $var_qt_URL = "https://github.com/orestonce/install-qt/releases/download/qt5.15.7/Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104.7z"
              $var_mingw_URL = "https://github.com/orestonce/install-qt/releases/download/qt5.15.7/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z"
              $var_qt_dir_name = "Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull"
              $var_mingw_dir_name = "mingw64"
              $var_md5_qt_7z = "21F5D197D4C49147A1FA2DBE3668D8B3"
              $var_md5_mingw_7z = "55C00CA779471DF6FAF1C9320E49B5A9"
              break
            }
            "Qt6.5.3-Windows-x86_64-MinGW13.2.0-ucrt-staticFull-20240527" {
              $var_qt_URL = "https://github.com/orestonce/install-qt/releases/download/qt6.5.3/Qt6.5.3-Windows-x86_64-MinGW13.2.0-ucrt-staticFull-20240527.7z"
              $var_mingw_URL = "https://github.com/orestonce/install-qt/releases/download/qt6.5.3/x86_64-13.2.0-release-posix-seh-ucrt-rt_v11-rev1.7z"
              $var_qt_dir_name = "Qt6.5.3-Windows-x86_64-MinGW13.2.0-ucrt-staticFull"
              $var_mingw_dir_name = "mingw64"
              $var_md5_qt_7z = "7DAAB484962835718E49F908845328F6"
              $var_md5_mingw_7z = "6278347DD0C9FD4FDF55665C0CAA9A87"
              break
            }
            "Qt6.7.2-Windows-x86_64-MinGW13.2.0-ucrt-20240621" {
              $var_qt_URL = "https://github.com/orestonce/install-qt/releases/download/qt6.7.2/Qt6.7.2-Windows-x86_64-MinGW13.2.0-ucrt-20240621.7z"
              $var_mingw_URL = "https://github.com/orestonce/install-qt/releases/download/qt6.7.2/x86_64-13.2.0-release-posix-seh-ucrt-rt_v11-rev1.7z"
              $var_qt_dir_name = "Qt6.7.2-Windows-x86_64-MinGW13.2.0-ucrt"
              $var_mingw_dir_name = "mingw64"
              $var_md5_qt_7z = "7EF7F919DB58C0A81A66DCD71803AFA9"
              $var_md5_mingw_7z = "6278347DD0C9FD4FDF55665C0CAA9A87"
              break
            }
            default {
               echo "invalid version value: ${{ inputs.version }}"
               exit -1
               break
            }
          }
          $var_qt_7z = $var_qt_URL.Substring($var_qt_URL.lastIndexOf('/')+1)
          $var_mingw_7z = $var_mingw_URL.Substring($var_mingw_URL.lastIndexOf('/')+1)
     
          New-Item -ItemType Directory -Force -Path ${{ inputs.dir }}
          cd ${{ inputs.dir }}
          Invoke-WebRequest -URI $var_qt_URL    -OutFile $var_qt_7z
          Invoke-WebRequest -URI $var_mingw_URL -OutFile $var_mingw_7z
          
          dir $var_qt_7z
          dir $var_mingw_7z
          
          $calculatedHash1 = (Get-FileHash -Path $var_qt_7z -Algorithm MD5).Hash
          $calculatedHash2 = (Get-FileHash -Path $var_mingw_7z -Algorithm MD5).Hash
          
          Write-Host "calculatedHash1 $calculatedHash1"
          Write-Host "calculatedHash2 $calculatedHash2"
          
          if (-not $var_md5_qt_7z) {
            Write-Host "skip check md5 var_md5_qt_7z"
          } elseif ($calculatedHash1 -ne $var_md5_qt_7z) {
            Write-Host "MD5 check error calculatedHash1: $calculatedHash1, var_md5_qt_7z: $var_md5_qt_7z"
            exit -2
          }
          
          if (-not $var_md5_mingw_7z) {
            Write-Host "skip check md5 var_md5_mingw_7z"
          } elseif ($calculatedHash2 -ne $var_md5_mingw_7z) {
            Write-Host "MD5 check error calculatedHash2: $calculatedHash2, var_md5_mingw_7z: $var_md5_mingw_7z"
            exit -3
          }
     
          7z x $var_qt_7z
          7z x $var_mingw_7z
      
          Remove-Item -Recurse -Force $var_qt_7z
          Remove-Item -Recurse -Force $var_mingw_7z
        
          if ( $var_qt_dir_name -ne 'qt_install') {
            move $var_qt_dir_name qt_install
          }
          if ( $var_mingw_dir_name -ne 'mingw_install') {
            move $var_mingw_dir_name mingw_install
          }
      - name: setup Qt env, windows
        shell: powershell
        if: runner.os == 'windows'
        run: |
          cd ${{ inputs.dir }}
          $oldContent = Get-Content -Path $env:GITHUB_PATH
          Clear-Content -Path $env:GITHUB_PATH
          Add-Content $env:GITHUB_PATH "${PWD}\qt_install\bin"
          Add-Content $env:GITHUB_PATH "${PWD}\mingw_install\bin"
          $oldContent | Add-Content -Path $env:GITHUB_PATH
          if (Test-Path "qt_install\QQtPatcher.exe") {
            echo ">>>>>>>run QQtPatcher.exe"
            .\qt_install\QQtPatcher.exe
          }
          
      - name: install Qt to dir, macos
        shell: bash
        if: runner.os == 'macos' && steps.install_qt.outputs.cache-hit != 'true'
        run: |
          set -x
          set -e
          case ${{ inputs.version }} in
            "Qt5.15.6-macOS-x86_64-AppleClang12.0.5-noFramework-20220914")
                var_qt_URL="https://github.com/orestonce/action/releases/download/qt-static5.15.6/Qt5.15.6-macOS-x86_64-AppleClang12.0.5-noFramework-20220914.tar.xz"
                var_qt_dir_name="Qt5.15.6-macOS-x86_64-AppleClang12.0.5-noFramework"
                ;;
            "Qt5.15.14-macOS-Universal-AppleClang15.0.0-noFramework-20240527")
                var_qt_URL="https://github.com/orestonce/action/releases/download/qt5.15.14/Qt5.15.14-macOS-Universal-AppleClang15.0.0-noFramework-20240527.tar.xz"
                var_qt_dir_name="Qt5.15.14-macOS-Universal-AppleClang15.0.0-noFramework"
                ;;
            "Qt6.7.2-macOS-Universal-AppleClang15.0.0-noFramework-20240621")
                var_qt_URL="https://github.com/orestonce/install-qt/releases/download/qt6.7.2/Qt6.7.2-macOS-Universal-AppleClang15.0.0-noFramework-20240621.tar.xz"
                var_qt_dir_name="Qt6.7.2-macOS-Universal-AppleClang15.0.0-noFramework"
                ;;
            *)
                echo "invalid version value: ${{ inputs.version }}"
                exit -1
                ;;
          esac
          mkdir -p ${{ inputs.dir }} && cd ${{ inputs.dir }}
          var_qt_xz=${var_qt_URL##*/}
          curl -L $var_qt_URL -o $var_qt_xz
          tar xf $var_qt_xz
          if [ $var_qt_dir_name != "qt_install" ]; then
            mv $var_qt_dir_name qt_install
          fi
      - name: setup Qt env, macos
        shell: bash
        if: runner.os == 'macos'
        run: |
          cd ${{ inputs.dir }}/qt_install/bin/
          chmod +x *
          echo "$(pwd)" >> $GITHUB_PATH