# This is a basic workflow to help you get started with Actions

name: push-build-check

# Controls when the workflow will run
on: push
jobs:
  windows-test:
    strategy:
      matrix:
        version: [Qt4.8.7-Windows-x86-MinGW4.9.4-20200104, Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104, Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104, Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104]
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install qt
        uses: orestonce/install-qt@main
        with:
          version: ${{ matrix.version }}
      - name: qmake
        run: |
          qmake -v
  macos-test:
    strategy:
      matrix:
        version: [Qt5.15.14-macOS-Universal-AppleClang15.0.0-noFramework-20240527]
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install qt
        uses: orestonce/install-qt@main
        with:
          version: ${{ matrix.version }}
      - name: qmake
        run: |
          qmake -v