# This is a basic workflow to help you get started with Actions

name: push-build-check

# Controls when the workflow will run
on: push
jobs:
  windows-test:
    strategy:
      matrix:
        version: [Qt4.8.7-Windows-x86-MinGW4.9.4-20200104, Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104, Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104, Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104, Qt6.7.2-Windows-x86_64-MinGW13.2.0-ucrt-20240621]
        example_proj_url: ["https://github.com/orestonce/install-qt/releases/download/etc/helloworld.zip"]
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install qt
        uses: orestonce/install-qt@dev
        with:
          version: ${{ matrix.version }}
      - name: command test
        run: |
          qmake -query
          gcc -v
          g++ -v
      - name: build test
        run: |
          $var_proj_7z = '${{ matrix.example_proj_url }}'.Substring('${{ matrix.example_proj_url }}'.lastIndexOf('/')+1)
          $var_proj_dir = $var_proj_7z.subString(0, $var_proj_7z.lastIndexOf('.'))
          
          Invoke-WebRequest -URI ${{ matrix.example_proj_url }} -OutFile $var_proj_7z
          
          dir $var_proj_7z
          7z x $var_proj_7z
          dir .
          cd $var_proj_dir
          dir .
          qmake -makefile
          make
  macos-test:
    strategy:
      matrix:
        os: [macos-14, macos-13]
        version: [Qt5.15.14-macOS-Universal-AppleClang15.0.0-noFramework-20240527, Qt6.7.2-macOS-Universal-AppleClang15.0.0-noFramework-20240621]
        example_proj_url: ["https://github.com/orestonce/install-qt/releases/download/etc/helloworld.zip"]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install qt
        uses: orestonce/install-qt@dev
        with:
          version: ${{ matrix.version }}
      - name: command test
        run: |
          qmake -query
          clang -v
          clang++ -v
      - name: build test
        run: |
          set -x
          set -e
          temp_str="${{ matrix.example_proj_url }}"
          var_proj_7z=${temp_str##*/}
          var_proj_dir="${var_proj_7z%%.*}"
          
          curl -L ${{ matrix.example_proj_url }} > $var_proj_7z
          
          find . -name toolchain.prf
          
          #wget Qt5.15.14-macOS-Universal-AppleClang15.0.0-noFramework\mkspecs\features\
          
          ls $var_proj_7z
          7z x $var_proj_7z
          ls .
          cd $var_proj_dir
          ls .
          qmake -makefile -Wall
          make
          ls .
          file ${var_proj_dir}.app/Contents/MacOS/${var_proj_dir}